import "./globals.css";
import SlideBar from "./components/SlideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <SlideBar/>
        <div style={{ margin: '0 auto'}}>
          {children}
        </div>
      </body>
    </html>
  );
}
